name: Deploy Development

on:
  push:
    branches:
      - develop  # Trigger on any push to the develop branch

permissions:
  id-token: write  # Required for authentication
  pages: write      # Required for GitHub Pages deployment

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Static Website
        run: npx parcel build src/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
